# Sektion: Neue Raeume A (schmiede/sternwarte/akademie/taverne)
RAEUME_NEU_A = {
    "schmiede": {
        "name": "Schmiede der Archive",
        "emoji": "⚒️",
        "beschreibung": "Eine mächtige Schmiede mit loderndem Feuer und gluehenden Kohlen, wo Daten zu Archiven verdichtet werden. Hier lernst du tar, gzip und zip zu meistern.",
        "ausgaenge": {"festung": "Festung"},
        "ascii_art": [
            "    *   F E U E R   *   ",
            "   /|\\   Esse    /|\\  ",
            "  [===== Amboss =====]  ",
            "  |~~~~  Glut  ~~~~~|  ",
            "  |___  SCHMIEDE  ___|  ",
        ],
        "npc": {
            "name": "Schmiedin Rosa",
            "bild": "🔨",
            "dialoge": [
                "Willkommen in der Schmiede der Archive! Ich bin Rosa, Hueterin der Archivkunst. Hier formen wir nicht nur Metall, sondern auch Daten! Das wichtigste Werkzeug ist 'tar'. Erstelle dein erstes Archiv: tar -czvf archiv.tar.gz buecher.txt - Merke: c=create, z=gzip, v=verbose, f=filename!",
                "Sehr gut! Jetzt lernst du Archivinhalte zu lesen und zu entpacken. Mit 'tar -tzvf archiv.tar.gz' listest du alle Dateien ohne zu entpacken - immer zuerst schauen was drin ist! Dann mit 'tar -xzvf archiv.tar.gz' entpackst du: x=extract. Das Trio c=erstellen, t=auflisten, x=entpacken ist der Kern von tar!",
                "Ausgezeichnet, Archivschmiedin Mia! Du beherrschst das gesamte Arsenal: tar (c/t/x fuer alles rund ums Archiv), gzip und gunzip fuer Einzeldateien (.gz), zip und unzip fuer Windows-Kompatibilitaet. Backups und Dateiuebertragungen werden dich nie mehr schrecken!",
            ],
        },
        "quests": [
            {
                "id": "tar_create",
                "ziel": "Erstelle Archiv: tar -czvf archiv.tar.gz buecher.txt",
                "check": lambda cmd, out, p: bool(cmd.split()) and cmd.split()[0] == 'tar' and '-c' in cmd,
                "belohnung": "📜 Schriftrolle des Archivs",
                "lernziel": "tar -czvf = create, zip, verbose, file. Wichtig fuer Backups!",
            },
            {
                "id": "tar_list",
                "ziel": "Zeige Archivinhalt: tar -tzvf archiv.tar.gz",
                "check": lambda cmd, out, p: bool(cmd.split()) and cmd.split()[0] == 'tar' and '-t' in cmd,
                "belohnung": "📜 Schriftrolle des Inhalts",
                "lernziel": "tar -t = list. Immer pruefen bevor man entpackt. Was ist drin?",
            },
            {
                "id": "tar_extract",
                "ziel": "Entpacke Archiv: tar -xzvf archiv.tar.gz",
                "check": lambda cmd, out, p: bool(cmd.split()) and cmd.split()[0] == 'tar' and '-x' in cmd,
                "belohnung": "📜 Schriftrolle der Befreiung",
                "lernziel": "tar -x = extract. Merke: c=create, t=table/list, x=extract.",
            },
            {
                "id": "gzip_comp",
                "ziel": "Komprimiere Datei: gzip lagerliste.txt",
                "check": lambda cmd, out, p: bool(cmd.split()) and cmd.split()[0] == 'gzip' and len(cmd.split()) >= 2,
                "belohnung": "📜 Schriftrolle der Verdichtung",
                "lernziel": "gzip komprimiert (.gz). Originaldatei wird ersetzt. gunzip zum Dekomprimieren.",
            },
            {
                "id": "gunzip_de",
                "ziel": "Dekomprimiere: gunzip lagerliste.txt.gz",
                "check": lambda cmd, out, p: bool(cmd.split()) and cmd.split()[0] == 'gunzip',
                "belohnung": "📜 Schriftrolle der Befreiung",
                "lernziel": "gunzip oder gzip -d dekomprimiert. zcat zeigt komprimierte Dateien ohne Entpacken.",
            },
            {
                "id": "zip_create",
                "ziel": "Erstelle ZIP: zip paket.zip *.txt",
                "check": lambda cmd, out, p: bool(cmd.split()) and cmd.split()[0] == 'zip' and len(cmd.split()) >= 3,
                "belohnung": "📜 Schriftrolle der Buendelung",
                "lernziel": "zip ist Windows-kompatibel. unzip zum Entpacken. Plattformuebergreifend!",
            },
        ],
        "dateien": [
            {
                "dateiname": "lagerliste.txt",
                "inhalt": "Vorraete in der Schmiede:\n- Eisen x 50\n- Kohle x 30\n- Kupfer x 20\n",
            },
        ],
    },
    "sternwarte": {
        "name": "Sternwarte des Systems",
        "emoji": "🔭",
        "beschreibung": "Ein hoher Beobachtungsturm mit riesigem Teleskop und freiem Blick auf das gesamte System. Astronom Kepler lehrt dich hier die Systembeobachtung mit uname, df, free und mehr.",
        "ausgaenge": {"bergpass": "Bergpass"},
        "ascii_art": [
            "   *  .  * Sterne *  .  *  ",
            "    .   *   .   *   .   *  ",
            "   |    ( Teleskop  )   |  ",
            "   |___/   Sockel   \\__|  ",
            "   [====  STERNWARTE ====] ",
        ],
        "npc": {
            "name": "Astronom Kepler",
            "bild": "⭐",
            "dialoge": [
                "Willkommen in der Sternwarte des Systems! Ich bin Kepler, Beobachter der digitalen Sterne. Wie ich Himmelskoerper analysiere, analysierst du dein System! Starte mit 'uname -a' - es zeigt Kernel-Version, Hostname und Architektur. Das Fundament jeder Systemanalyse!",
                "Hervorragend! Nun erkunden wir die Ressourcen. 'df -h' zeigt Festplattenplatz - h bedeutet human-readable, also GB und MB statt rohe Bytes. 'free -h' zeigt RAM-Nutzung, entscheidend fuer die Performance! 'du -sh *' zeigt welche Ordner am meisten Platz belegen. Diese drei Befehle retten jeden Administrator!",
                "Fantastisch! Du bist nun Systemastronom! Dein Werkzeugkasten: uname (System-Identitaet), df (Festplattenplatz), free (RAM-Nutzung), du (Ordner-Groessen), date (aktuelles Datum und Zeit), cal (Kalender), uptime (Laufzeit und Load Average). Mit diesen Werkzeugen kennst du deinen Server wie ich die Sterne!",
            ],
        },
        "quests": [
            {
                "id": "uname_stern",
                "ziel": "Zeige Systeminfo: uname -a",
                "check": lambda cmd, out, p: bool(cmd.split()) and cmd.split()[0] == 'uname',
                "belohnung": "📜 Schriftrolle des Universums",
                "lernziel": "uname -a: Kernel, Hostname, Architektur. uname -r = nur Kernel-Version.",
            },
            {
                "id": "df_stern",
                "ziel": "Zeige Festplattenplatz: df -h",
                "check": lambda cmd, out, p: bool(cmd.split()) and cmd.split()[0] == 'df',
                "belohnung": "📜 Schriftrolle des Raums",
                "lernziel": "df -h zeigt Festplattenplatz. -h = human-readable (GB/MB). Wichtig fuer Admins!",
            },
            {
                "id": "free_stern",
                "ziel": "Zeige RAM-Nutzung: free -h",
                "check": lambda cmd, out, p: bool(cmd.split()) and cmd.split()[0] == 'free',
                "belohnung": "📜 Schriftrolle des Gedaechtnisses",
                "lernziel": "free -h zeigt RAM-Nutzung. Buff/Cache kann freigegeben werden. Swap = Auslagerungsdatei.",
            },
            {
                "id": "du_stern",
                "ziel": "Zeige Ordnergroessen: du -sh *",
                "check": lambda cmd, out, p: bool(cmd.split()) and cmd.split()[0] == 'du',
                "belohnung": "📜 Schriftrolle der Groesse",
                "lernziel": "du -sh * = disk usage, summary, human-readable. du -sh /home/*/ zeigt Home-Groessen.",
            },
            {
                "id": "date_stern",
                "ziel": "Zeige Datum und Zeit: date",
                "check": lambda cmd, out, p: bool(cmd.split()) and cmd.split()[0] == 'date',
                "belohnung": "📜 Schriftrolle der Zeit",
                "lernziel": "date zeigt Datum/Zeit. date '+%Y-%m-%d' = ISO-Format. Sehr nuetzlich in Skripten.",
            },
            {
                "id": "cal_stern",
                "ziel": "Zeige Kalender: cal",
                "check": lambda cmd, out, p: bool(cmd.split()) and cmd.split()[0] == 'cal',
                "belohnung": "📜 Schriftrolle des Kalenders",
                "lernziel": "cal zeigt den Monat. cal -3 = 3 Monate. cal 2024 = ganzes Jahr.",
            },
            {
                "id": "uptime_stern",
                "ziel": "Zeige Systemlaufzeit: uptime",
                "check": lambda cmd, out, p: bool(cmd.split()) and cmd.split()[0] == 'uptime',
                "belohnung": "📜 Schriftrolle der Ausdauer",
                "lernziel": "uptime: Laufzeit und Load Average (1/5/15 Min). <CPU-Kerne = entspannt.",
            },
        ],
        "dateien": [
            {
                "dateiname": "sternenkarte.txt",
                "inhalt": "=== Systembeobachtung ===\nuname, df, free, du, date, cal\n",
            },
        ],
    },
    "akademie": {
        "name": "Akademie der Variablen",
        "emoji": "🎓",
        "beschreibung": "Eine ehrwuerdige Universitaet mit Saeulengaengen und Bueregalen voller Wissen. Professorin Euler enthuellt hier die Geheimnisse der Umgebungsvariablen und des export-Befehls.",
        "ausgaenge": {"hafen": "Hafen", "magierschule": "Magierschule"},
        "ascii_art": [
            "  | |  AKADEMIE  | |   ",
            "  |=|  _________  |=| ",
            "  | | | Variablen| | | ",
            "  | | |__________| | | ",
            "  | |  Saeulenhalle | | ",
            "  |__|______________|__| ",
        ],
        "npc": {
            "name": "Professorin Euler",
            "bild": "📐",
            "dialoge": [
                "Guten Tag! Ich bin Professorin Euler, und ich heisse dich herzlich willkommen an der Akademie der Variablen! Umgebungsvariablen sind magische Botschaften, die dein System dir bereitstellt. Die wichtigste: $HOME! Probiere: echo $HOME - Das Dollarzeichen sagt Linux: Zeig mir den Wert dieser Variable!",
                "Wunderbar! Weiter geht es mit deinem Benutzernamen: echo $USER zeigt wer du bist, perfekt fuer Skripte! Und echo $PATH zeigt alle Ordner, wo Linux nach Programmen sucht, getrennt durch Doppelpunkte. Wenn ein Programm nicht gefunden wird, liegt es oft am falschen $PATH!",
                "Exzellent! Jetzt erschaffst du eigene Variablen! Mit 'export ZAUBER=Expecto' setzt du eine Variable und machst sie fuer alle Unterprozesse sichtbar. Ohne export ist sie nur in deiner Shell bekannt. 'env | head -10' zeigt alle aktuell gesetzten Variablen - eine ganze Schatzkammer!",
                "Magnifico! Du hast die Akademie der Variablen erfolgreich abgeschlossen! Die wichtigsten Variablen: $HOME (Heimatverzeichnis), $USER (Benutzername), $PATH (Suchpfade fuer Programme), $SHELL (deine aktive Shell). Mit export teilst du Variablen mit Unterprogrammen. printenv prueft einzelne Variablen gezielt. Die Magierschule wartet!",
            ],
        },
        "quests": [
            {
                "id": "home_akad",
                "ziel": "Zeige Home: echo $HOME",
                "check": lambda cmd, out, p: bool(cmd.split()) and cmd.split()[0] == 'echo' and 'HOME' in cmd,
                "belohnung": "📜 Schriftrolle des Heims",
                "lernziel": "$HOME = dein Home-Verzeichnis. cd ohne Argumente = cd $HOME.",
            },
            {
                "id": "user_akad",
                "ziel": "Zeige Benutzer: echo $USER",
                "check": lambda cmd, out, p: bool(cmd.split()) and cmd.split()[0] == 'echo' and 'USER' in cmd,
                "belohnung": "📜 Schriftrolle des Namens",
                "lernziel": "$USER enthaelt Benutzernamen. $UID = User-ID. Nuetzlich in Skripten.",
            },
            {
                "id": "path_akad",
                "ziel": "Zeige Suchpfad: echo $PATH",
                "check": lambda cmd, out, p: bool(cmd.split()) and cmd.split()[0] == 'echo' and 'PATH' in cmd,
                "belohnung": "📜 Schriftrolle der Wege",
                "lernziel": "$PATH: Ordner wo Linux Programme sucht. : als Trenner. which zeigt welcher Pfad genutzt.",
            },
            {
                "id": "export_akad",
                "ziel": "Setze Variable: export ZAUBER='Expecto'",
                "check": lambda cmd, out, p: bool(cmd.split()) and cmd.split()[0] == 'export',
                "belohnung": "📜 Schriftrolle der Schoepfung",
                "lernziel": "export macht Variablen fuer Kind-Prozesse sichtbar. Ohne export: nur in Shell sichtbar.",
            },
            {
                "id": "env_akad",
                "ziel": "Zeige Umgebung: env | head -10",
                "check": lambda cmd, out, p: bool(cmd.split()) and cmd.split()[0] == 'env',
                "belohnung": "📜 Schriftrolle der Umgebung",
                "lernziel": "env zeigt alle gesetzten Variablen. printenv VARIABLE zeigt einzelne.",
            },
            {
                "id": "printenv_akad",
                "ziel": "Pruefe Variable: printenv HOME",
                "check": lambda cmd, out, p: bool(cmd.split()) and cmd.split()[0] == 'printenv',
                "belohnung": "📜 Schriftrolle der Pruefung",
                "lernziel": "printenv NAME zeigt Wert. Gibt nichts aus wenn Variable nicht gesetzt.",
            },
        ],
        "dateien": [
            {
                "dateiname": "variablen.txt",
                "inhalt": "Wichtige Umgebungsvariablen:\n$HOME - Home-Verzeichnis\n$USER - Benutzername\n$PATH - Suchpfad\n$SHELL - Shell-Pfad\n",
            },
        ],
    },
    "taverne": {
        "name": "Taverne der Tricks",
        "emoji": "🍺",
        "beschreibung": "Eine gemütliche Taverne mit Holzfaessern, Kerzen und warmem Herdfeuer. Wirt Gottfried kennt alle Shell-Tricks und teilt sie gerne bei einem Becher Met.",
        "ausgaenge": {"turm": "Turm"},
        "ascii_art": [
            "  [======= TAVERNE =======]  ",
            "  | Fass |  Theke  | Fass |  ",
            "  | [=]  | [=] [=] |  [=] |  ",
            "  |    * Kerzenschein *    |  ",
            "  |______warm und gut______|  ",
        ],
        "npc": {
            "name": "Wirt Gottfried",
            "bild": "🧙",
            "dialoge": [
                "Willkommen in der Taverne der Tricks! Ich bin Gottfried, Wirt und Meister der verborgenen Shell-Kuenste! Setz dich und lass dir von mir die Geheimnisse der Profis verraten! Starte mit: history | tail -20 - Du siehst deine letzten 20 Befehle. Mit !42 fuehrst du Befehl 42 erneut aus. Strg+R sucht im Verlauf!",
                "Bravo! Jetzt die echten Profitricks: Mit 'alias ll=ls -la' erstellst du eigene Kurzbefehle, in ~/.bashrc gespeichert bleiben sie dauerhaft! 'type ls' zeigt ob ls ein Programm, Alias oder Shell-Built-in ist, unverzichtbar zur Fehlersuche. 'which python3' zeigt den vollen Pfad, wichtig bei mehreren installierten Versionen!",
                "Prost auf dich, wahrer Shell-Meister! Meine besten Geheimtipps: history und Strg+R fuer blitzschnelle Befehlssuche, alias spart Tipparbeit, type und which spueren Programme auf, echo $? prueft den letzten Exit-Code (0=Erfolg!), tee zeigt Ausgabe gleichzeitig an und speichert sie. Und vergiss nie die Tab-Taste fuer Autovervollstaendigung!",
            ],
        },
        "quests": [
            {
                "id": "history_tav",
                "ziel": "Zeige Verlauf: history | tail -20",
                "check": lambda cmd, out, p: bool(cmd.split()) and cmd.split()[0] == 'history',
                "belohnung": "📜 Schriftrolle der Erinnerung",
                "lernziel": "history zeigt alle Befehle mit Nummern. !42 = Befehl 42. !! = letzter. Strg+R sucht.",
            },
            {
                "id": "alias_tav",
                "ziel": "Erstelle Kurzbefehl: alias ll='ls -la'",
                "check": lambda cmd, out, p: bool(cmd.split()) and cmd.split()[0] == 'alias',
                "belohnung": "📜 Schriftrolle der Abkuerzung",
                "lernziel": "alias erstellt Kurzbefehle. In ~/.bashrc = dauerhaft. alias ohne Args = alle anzeigen.",
            },
            {
                "id": "type_tav",
                "ziel": "Was ist ls? type ls",
                "check": lambda cmd, out, p: bool(cmd.split()) and cmd.split()[0] == 'type' and len(cmd.split()) >= 2,
                "belohnung": "📜 Schriftrolle der Wahrheit",
                "lernziel": "type zeigt ob Programm, Alias, Shell-Funktion oder Built-in. Nuetzlich zur Fehlersuche.",
            },
            {
                "id": "which_tav",
                "ziel": "Wo liegt Python? which python3",
                "check": lambda cmd, out, p: bool(cmd.split()) and cmd.split()[0] == 'which' and len(cmd.split()) >= 2,
                "belohnung": "📜 Schriftrolle des Pfades",
                "lernziel": "which zeigt vollen Pfad. Gut wenn mehrere Versionen installiert sind.",
            },
            {
                "id": "exitcode_tav",
                "ziel": "Pruefe Exit-Code: echo $?",
                "check": lambda cmd, out, p: bool(cmd.split()) and cmd.split()[0] == 'echo' and '?' in cmd,
                "belohnung": "📜 Schriftrolle des Ergebnisses",
                "lernziel": "$? = Exit-Code des letzten Befehls. 0=Erfolg, sonst Fehler. In Skripten sehr wichtig!",
            },
            {
                "id": "tee_tav",
                "ziel": "Zeige und speichere: ls | tee liste.txt",
                "check": lambda cmd, out, p: 'tee' in cmd,
                "belohnung": "📜 Schriftrolle des T-Stuecks",
                "lernziel": "tee zeigt Ausgabe UND speichert gleichzeitig. Wie ein T-Stueck in einer Wasserleitung!",
            },
        ],
        "dateien": [
            {
                "dateiname": "trickliste.txt",
                "inhalt": "Shell-Tricks:\nStrg+C - Abbrechen\nStrg+L - Leeren\nStrg+A - Zeilenanfang\nTab - Autovervollstaendigung\nPfeil-Oben - Vorheriger Befehl\n",
            },
        ],
    },
}
